### PR TITLE
Dropflow: rainflow incremental and stateful version 

### PR DESCRIPTION
**Pull request by Daveonwave**
Hello,

I’ve been using the Rainflow algorithm to extract cycles from a battery’s profile and calculate system degradation. However, since my application operates in real-time, the battery’s evolution is processed step by step. Applying the Rainflow algorithm at each step (or even at intervals) was a total pain in terms of time complexity.

To address this, I explored your code and modified the Rainflow algorithm to be stateful. This allows it to retain previously computed cycles and handle time-series data incrementally, processing one data point at a time rather than requiring the entire dataset upfront.

In this pull request, I am sharing the code I developed. I’m not sure if this approach aligns with your vision for the library, but feel free to incorporate it if you find it useful. I have tried to follow your implementation and documentation structures, but I’m happy to clarify anything that may need further explanation.

Cheers,

### CODE REVIEW

**Comment by iamlikeme** [comment]
Hi, it's a cool idea. Do you have some usage example with demonstrates how to use it in a real-time application (for example with the time series from the tests: `[-2, 1, -3, 5, -1, 3, -4, 4, -2]`)?

**Comment by Daveonwave** [comment]
Hi Piotr,

I updated the code, including the tests provided in the `tests` folder. All the tests were completely passed, but two, one from TEST_CASE_2 and one from TEST_CASE_3, couldn't be solved properly. 

The way to use the algorithm is this:
```python
dropflow = Dropflow()
dropflow.reset()
for idx, point in enumerate(series):
    dropflow.add_point(x=point, idx=idx)
cycles = dropflow.extract_all_cycles()
```

The class `Dropflow` is equipped also with a method called `extract_new_cycles()`, which allows computing only cycles from the newest points without storing closed ones. Instead, the method `extract_all_cycles()` stores the closed cycles, i.e. the half cycles occurring at the beginning of the time-series and the full cycles.

I had to think a bit also about how to consider the last point added to the series. 
Indeed, in the Rainflow code the last point is always considered a reversal, and this is a reasonable assumption knowing that the series ends there. However, in my situation, I had to add the last point as a _temporary_ reversal, since I cannot know in advance what will come next. 

To do so, I used the `_stopper` attribute, which is updated as soon as a new sample is added, and it is not considered as a proper reversal, but is still used to compute new cycles. Furthermore, the `ignore_stopper` parameter in the `extract_all_cycles()` method allows us to not consider that point at all for cycle computation.

In the end, I run a couple of experiments comparing dropflow and rainflow in a setting where is required to incrementally compute cycles at each simulator step. In this scenario, having a stateful rainflow algorithm is highly beneficial in terms of time complexity. 

Here some results:

- 35000 samples: **rainflow** ~01:38 min vs. **dropflow** ~00:36 min (error MSE: 9.29e-12 )
- 97000 samples: **rainflow** ~21:26 min vs. **dropflow** ~06:02 min (error MSE: 3.99e-12 )

Let me know if you need further information, results, or clarifications.

Cheers

**Comment by iamlikeme** [comment]
Function `rainflow.extract_cycles` works with any iterable, so it might be an iterator that yields values from a queue. This would support real-time scenarios. Here is an example script which extracts cycles from a time series that is generated at a rate of 5 values per second:

```python
import random
import time
from queue import Queue
from threading import Thread

import rainflow

queue = Queue()

def generate_points():
    for _ in range(50):
        queue.put(random.random())
        time.sleep(0.2)
    
    queue.put(None)


t = Thread(target=generate_points)
t.start()

series = iter(queue.get, None)
for cycle in rainflow.extract_cycles(series):
    print(cycle)
```

Would it work for your use case?

I have also tried to reproduce the benchmark results you provided. I measured times for a single run using IPython `%%time` magic, so it is not super exact but gives some idea:

```python
In [1]: import random
   ...: 
   ...: import dropflow
   ...: import rainflow
   ...: 
   ...: series = [random.random() for _ in range(35000)]

In [2]: %%time
   ...: result_1 = list(rainflow.extract_cycles(series))
   ...: 
   ...: 
CPU times: user 11 ms, sys: 0 ns, total: 11 ms
Wall time: 11 ms

In [3]: %%time
   ...: d = dropflow.Dropflow()
   ...: for idx, x in enumerate(series):
   ...:     d.add_point(x, idx)
   ...: 
   ...: result_2 = list(d.extract_all_cycles())
   ...: 
   ...: 
CPU times: user 47.5 ms, sys: 2.03 ms, total: 49.5 ms
Wall time: 49.1 ms

In [4]: len(result_1), len(result_2)
Out[4]: (11676, 15960)
```

Both `rainflow` and `dropflow` used less than 50 ms to process 35000 points, which is orders of magnitude less than than what you observed (98 and 36 seconds). I assume your benchmark consisted of many other operations, unrelated to cycle extraction, which consumed most of the time.

I also observe that `rainflow` and `dropflow` produce a different number of cycles, but I haven't looked into why.

**Comment by Daveonwave** [comment]
Hi Piotr,
I appreciate your experiments and everything you said is correct. Actually, my scenario is a bit different. 

In particular, I have a simulator of a battery which includes an algorithm used to compute its degradation ([here](https://ieeexplore.ieee.org/document/7488267) the algorithm paper) that requires to extract all the charging/discharging cycles until the beginning of the battery's operational life. To extract cycles it uses the rainflow algorithm. 
To monitor the system in real-time, I need an estimate of the degradation at each simulation step. Thus, I have to call this algorithm and compute the _rainflow_ at each simulation step adding to the series the new generated sample. However, to extract all the cycles from the beginning of the series, the rainflow has to consider every time the entire history of samples. 

To give you an idea of how my code works recalling your experiment, it is something like this:

```python3
In [1]: import random
   ...: import dropflow
   ...: import rainflow
   ...: 
   ...: series = [random.random() for _ in range(35000)]

In [2]: %%time
   ...: for i in range(len(series)):
   ...:     result_1 = list(rainflow.extract_cycles(series[:i]))
   ...: 
CPU times: user 3min 59s, sys: 2.65 s, total: 4min 2s
Wall time: 4min 3s

In [3]: %%time
   ...: d = dropflow.Dropflow()
   ...: for idx, x in enumerate(series):
   ...:     d.add_point(x, idx)
   ...:     result_2 = list(d.extract_all_cycles()
   ...: 
CPU times: user 3.91 s, sys: 46.4 ms, total: 3.96 s
Wall time: 3.96 s

In [4]: len(result_1), len(result_2)
Out[4]: (11695, 11694)
```

As you can notice in this case the _extract_cycle()_ function is called 35000 times, each time for a list of increasing length. Instead, with _dropflow_ you can simply add the new sample of the series (without passing the entire history each time) and the computation will consider only previous half cycles and new added reversals.
In fact, the reason why I needed something stateful and I came out with _Dropflow_, is to not compute at each simulation step the _rainflow_ algorithm on the entire history of generated samples. 
With respect to results of my previous message, here the computation in charge to the simulator is omitted, that's why the consumed time is lower.

Furthermore, from this snippet of code, you can notice that the extracted cycle differ only of one unit. This is probably due to the way I handle the reversals, since having an incremental series of points I cannot consider the last point as a reversal, otherwise I would mark all the new samples as reversals.

I hope to have clarified everything, but let me know if you need further results and clarifications.

**Comment by Daveonwave** [comment]
Hi Piotr,
thank you for your experiment. All the things you said are correct. Actually, my application differs a little bit from your example.

I will try to explain my specific application. I implemented a simulator of a battery that employs a degradation model ([here](https://ieeexplore.ieee.org/abstract/document/7488267)) to estimate the battery degradation at each simulation step. This degradation model requires to collect charging/discharging cycles to compute the current degradation of the system. To do so, it employs the rainflow algorithm.

As you may notice, this computation has to be done at each simulation step on all the history of samples plus the newly generated sample. For example: 
- step $t=1$ => `len(series) == 1`
- step $t=2$ => `len(series) == 2`
- step $t=3$ => `len(series) == 3`
- ...

Hence, at each simulation step, I have to compute the `rainflow` algorithm on a list of increasing lengths. 
Recalling your experiment, the comparison I would evaluate between `rainflow` and `dropflow` is the following:

```python3
In [1]: import random
   ...: import dropflow
   ...: import rainflow
   ...: 
   ...: series = [random.random() for _ in range(35000)]

In [2]: %%time
   ...: for i in range(len(series)):
   ...:    result_1 = list(rainflow.extract_cycles(series[:i]))
   ...: 
CPU times: user 3min 59s, sys: 2.65 s, total: 4min 2s
Wall time: 4min 3s

In [3]: %%time
   ...: d = dropflow.Dropflow()
   ...: 
   ...: for idx, x in enumerate(series):
   ...:     d.add_point(x, idx)
   ...:     result_2 = list(d.extract_all_cycles()
   ...: 
CPU times: user 3.8 s, sys: 457 ms, total: 4.26 s
Wall time: 4.26 s

In [4]: len(result_1), len(result_2)
Out[4]: (11695, 11694)
```
As you may notice from the snippet above, with `rainflow` I have to pass at each step the entire history of samples, while with `dropflow` I just need to add the last sample and extract the cycles. Indeed, being a stateful version of `rainflow`, `dropflow` computes the cycles only among old half cycles and new reversal points, without re-computing the previously seen closed cycles. 
This accelerates a lot the computation. Indeed, you can check the time consumption statistics for each method from the script and you can imagine why I needed something stateful for my application.  

You can also notice that the extracted cycles differ by just one unit at the last iteration step. This is probably due to the fact that with `dropflow` I cannot consider the last added sample as a reversal, otherwise it would mark each new point as a reversal. I guess that the difference is related to this fact.

I hope to have addressed all your doubts. Let me know if you need further clarification.

**Comment by iamlikeme** [comment]
Thanks for explaining the details - now I understand the difference in performance between rainflow and dropflow. Your use case seems very special - I've never seen anyone using rainflow algorithm this way - therefore I think it should not be included in the `rainflow` package unless there is a clear demand for it in the community. Still, thank you for sharing your code - perhaps someone will discover this PR and find it useful.

I would also like to offer a somewhat different approach to your use case, which does not require recalculating the entire series for each successive point. We can use `rainflow.extract_cycles` to construct a pandas data frame like this:

```python
In [1]: import random
   ...: import rainflow
   ...: import pandas as pd

In [2]: series = [random.random() for _ in range(35000)]

In [3]: df = pd.DataFrame(
   ...:     rainflow.extract_cycles(series),
   ...:     columns=["range", "mean", "count", "i_start", "i_end"],
   ...: )

In [4]: df
Out[4]: 
          range      mean  count  i_start  i_end
0      0.049600  0.852482    0.5        0      1
1      0.078532  0.866948    0.5        1      2
2      0.125555  0.620276    1.0        3      4
3      0.489376  0.661527    0.5        2      5
4      0.562859  0.698269    0.5        5      7
...         ...       ...    ...      ...    ...
11657  0.991189  0.499847    0.5    34916  34988
11658  0.818862  0.413684    0.5    34988  34994
11659  0.714134  0.466048    0.5    34994  34997
11660  0.598473  0.408218    0.5    34997  34998
11661  0.138404  0.638253    0.5    34998  34999

[11662 rows x 5 columns]
```

Now we can very quickly find all cycles up to an arbitrary point in the series, e.g.

```python
In [5]: %%time
   ...: full_cycles = (df["i_end"] < 23000) & (df["count"] == 1.0)
   ...: half_cycles = (df["i_start"] < 23000) & (df["count"] == 0.5)
   ...: 
   ...: df[full_cycles | half_cycles]
CPU times: user 1.09 ms, sys: 952 μs, total: 2.05 ms
Wall time: 1.87 ms
Out[5]: 
          range      mean  count  i_start  i_end
0      0.049600  0.852482    0.5        0      1
1      0.078532  0.866948    0.5        1      2
2      0.125555  0.620276    1.0        3      4
3      0.489376  0.661527    0.5        2      5
4      0.562859  0.698269    0.5        5      7
...         ...       ...    ...      ...    ...
7666   0.623259  0.568657    1.0    22985  22997
7696   0.978937  0.501429    1.0    22896  22915
7746   0.999638  0.499997    1.0    14874  20245
11586  0.999925  0.499969    0.5     7287   9943
11654  0.999965  0.499989    0.5     9943  34774

[7671 rows x 5 columns]
```

Hope you find it helpful :slightly_smiling_face:

**Comment by Daveonwave** [comment]
I see your point and thank you for the feedback and the consideration given to my idea. 
Wish you the best!

**Pull request closed without merging**
